server:
  port: 10060
spring:
  application:
    name: user-server
  datasource:
    username: root
    password: root
    url: jdbc:mariadb://127.0.0.1:3306/rural?serverTimezone=Asia/Shanghai

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1