server:
  port: 10110
spring:
  application:
    name: user-consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
    registry-fetch-interval-seconds: 30 #默认是30s拉取时长，可以改小一些例如3s,4s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
feign:
  hystrix:
    enabled: true #开启feign对hystrix的支持 熔断开启
ribbon:
  connectionTimeOut: 500 #单位ms 默认1000ms 只是在feign需要中配置
  ReadTimeOut: 2000 #单位ms 默认1000 只是在feign需要中配置
