server:
  port: 10017
spring:
  #  过滤规则
  mvc:
    static-path-pattern: /static/**
  #  静态资源位置
  resources:
    static-locations: classpath:/static/
  application:
    name: rural-employment-consumer-server
  datasource:
    datasource:
    username: root
    password: root
    url: jdbc:mariadb://127.0.0.1:3306/rural?serverTimezone=Asia/Shanghai
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: admin
    password: admin
#度量指标监控与健康检查
management:
  endpoints:
    web:
      base-path: /actuator   # ##访问端点的根路径，默认 /actuator
      exposure:
        include: bus-refresh   #开启需要的端点，这里主要是用到refresh这个端点 ,'*'是除了shuntdown没有开启 也可以单独开启bus-refresh
      #   exclude:  #不需要启动的端点
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1